# This is a file which should run each of the other tests in turn.
# It is currently in the /tests/admin/ folder instead of /tests/ because importing was not working nicely
# 
# 
# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re
from admin import *

class MasterTestTouche(unittest.TestCase):
    #these are all the functions that are auto-generated by Selenium which are common to all the exported tests.
    def setUp(self):
        self.driver = webdriver.PhantomJS("/usr/local/bin/phantomjs")
        self.driver.implicitly_wait(30)
        self.base_url = "http://localhost/~touche"#this will be changed after the contest creation to "http://localhost/~touche/Test_Contest"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException, e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException, e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)
        
    #this is the main function that I'm actually writing.
    #hopefully this is in a logical order: create the contest, ensure that the first login forces the user to change the password, then log in properly and make sure everything is there, occasionally visiting things out of order to make sure users are directed to the correct order.
    #looks at admin first, then team, then judge
    def test_master_test_touche(self):
        #setup and admin tests
        CreateContestTests.CreateContestTests().test_create_contest_tests()
        self.base_url = "http://localhost/~touche/Test_Contest"
        AdminLoginTest.AdminLoginTest().test_admin_login_test()
        SetupContestTest.SetupContestTest().test_setup_contest_test()
        SetupProblemsTest.SetupProblemsTest().test_setup_problems_test()
        AddEditDeleteProblems.AddEditDeleteProblems().test_add_edit_delete_problems()
        DataSetsAndProblems.DataSetsAndProblems().test_data_sets_and_problems()
        SetupSiteTest.SetupSiteTest().test_setup_site_test()
        AddEditDeleteSites.AddEditDeleteSites().test_add_edit_delete_sites
        SetupTeamsTest.SetupTeamsTest().test_setup_team_test()
        AddEditDeleteTeams.AddEditDeleteTeams().test_add_edit_delete_teams
        
        
#this is also common to all the auto-generated code.
if __name__ == "__main__":
    unittest.main()